def gen_new_array(array):
    raise Exception("Something bad happened")
